security:
  # Hiérarchie des rôles
  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    ROLE_ADMIN: [ROLE_USER]
    ROLE_USER: []

  # Gestion des mots de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # Utilisateurs / providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
      logout:
        path: app_logout
        # target: app_home (décommenter si tu veux rediriger après logout)

      # Durée maximale de la session : 48 heures (48h × 3600s = 172800 secondes)
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 172800  # durée en secondes
        path: /
        always_remember_me: false

  # Contrôle d'accès basé sur les rôles
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
